### ISSUE TITLE
Broken URL 

### ISSUE THREAD

**Issue by richelbilderbeek** [yageek/Meschach#3]
The URL of the main header, `http://homepage.math.uiowa.edu/~dstewart/meschach‎` is broken.

![brokenurl](https://cloud.githubusercontent.com/assets/2098230/25940548/c505463a-3636-11e7-99c4-125660825ee9.png)

**Comment by osaether** [comment]
I believe there are som hidden characters in the URL. If I type it in manually it works:
http://homepage.math.uiowa.edu/~dstewart/meschach

**Comment by yageek** [comment]
It should work now. I put the URL as the website URL.
