### ISSUE TITLE
cmake file in win with VS only create .lib no dll

### ISSUE THREAD

**Issue by mahuichao** [yageek/Meschach#7]
Hello ,I have a question that confusing me.I cmake in the directory of Meschach,and It  create a VS project.Then I import the project to VS and build,but only come out .lib there is no dll,you know in VS I can not debug without dll ,so do you konw what should I do?

**Comment by yageek** [comment]
Did you try to change the last line of the `CMakeLists.txt` by:

```add_library(meschach SHARED ${sources_files})```

**Comment by mahuichao** [comment]
@yageek   YES  I tried,but there are some errors when I changed it.like:can not recognize external symbol :_MEM_COPY
